### ISSUE TITLE
Semaine du 20 mai 2019 manquante

### ISSUE THREAD

**Issue by ncheymol** [MicrosoftDocs/IntuneDocs.fr-fr#28]
Il manque la mise à jour du 20 mai 2019

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e712d5e3-1b32-74b8-3487-6a77bd7f49fb
* Version Independent ID: dac02fab-5c76-94dd-7c6c-1a484aa4e050
* Content: [Nouveautés de Microsoft Intune - Azure](https://docs.microsoft.com/fr-fr/intune/whats-new)
* Content Source: [intune/whats-new.md](https://github.com/MicrosoftDocs/IntuneDocs.fr-fr/blob/live/intune/whats-new.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by CeciAc** [comment]
Cher(ère) @ncheymol

Merci pour vos commentaires et vos suggestions.  

Le fichier est en cours de traduction. Nous publierons cet article prochainement.

Un grand merci pour votre aide. 

Cordialement,

L’équipe Microsoft DOCS Global Experience
