### ISSUE TITLE
Non complet

### ISSUE THREAD

**Issue by chagueh** [MicrosoftDocs/IntuneDocs.fr-fr#29]
Pour vérifier que le PC est bien enrôlé il faut aller dans la section 
"All devices" si elle n'est pas présente, alors elle n'est pas enrôlée à intune mais seulement à azure AD et ne recevra donc AUCUNE des politiques de gestion mise en place sur intune.... 

Si les équipes microsoft pouvaient compléter leur tutos cela serait génial :)

Même problème sur le tuto supprimer un w10 d'intune : 
https://docs.microsoft.com/fr-fr/intune-user-help/unenroll-your-device-from-intune-windows

Après avoir galéré pendant des semaines avec le support j'ai du me débrouiller seul pour trouver une solution, l'objectif était de réattribuer une machine a un nouvel utilisateur. 

Impossible sans passer par une suppression complete sur intune de toutes les entrées liées au poste ainsi qu'une suppression des clef de registre présentes sur ce dernier...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3d36fe11-e61e-fc71-aa23-006e09b9a469
* Version Independent ID: b030b0f9-4673-2196-6a6c-3ee3a4e2fcaa
* Content: [Démarrage rapide - Inscrire un appareil Windows 10 Desktop dans Microsoft Intune](https://docs.microsoft.com/fr-fr/intune/quickstart-enroll-windows-device#feedback)
* Content Source: [intune/quickstart-enroll-windows-device.md](https://github.com/MicrosoftDocs/IntuneDocs.fr-fr/blob/live/intune/quickstart-enroll-windows-device.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Bonjour @chagueh

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/IntuneDocs/issues/2533. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
